project:
  name: "avconv"
  description: "toolbox to manipulate, convert and stream multimedia content"
  github: "https://github.com/libav/libav"
  input_format: "*.mp4, *.mkv, *.avi, *.mov, *.flv, *.wmv, *.webm, *.mp3, *.aac, *.wav, *.ogg"
  test_format: "mp4"
  test_des: " - Contain a valid ftyp (File Type) box with a recognizable major brand and compatible brands.\n - Contain a moov (Movie) box, which holds essential metadata about the movie with at least one valid trak describing media.\n - Contain IDAT Chunk(s) (Image Data).\n - Contain an mdat (Media Data) box with the raw media samples.\n"
  test_encoding: "base64"
